tupla = (1, 4, 9, 16, 25)
print('Tupla inicial egenerada:', tupla)
num_add = int(input('Número que se desea añadir a la tupla: '))
print()
lista_p = list(tupla)
lista_p.append(num_add)
tupla_final = tuple(lista_p)
print('La tupla resultante es:', tupla_final)
print()
print(f'La longitud de la tupla es de {len(tupla_final)} elementos.')
print()
print('Los tres últimos elementos de la tupla son %s, %s y %s.' % (tupla_final[-3], tupla_final[-2], tupla_final[-1]))
print()